# Generated by Django 4.0.6 on 2022-09-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.IntegerField()),
                ('bookname', models.CharField(max_length=70)),
                ('author', models.CharField(max_length=80)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
